---
language: ruby
cache: bundler
rvm:
- 3.0.1
- 2.7.3
- 2.6.7
before_install:
- 'echo ''gem: --no-ri --no-rdoc --no-document'' > ~/.gemrc'
- gem install bundler
- source ${TRAVIS_BUILD_DIR}/ci/before_install.sh
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
- bundle exec rake spec:setup
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
addons:
  postgresql: '10'
