---
name: CI
on:
- push
- pull_request
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version:
        - '3.0'
        - '3.1'
        - '3.2'
        - '3.3'
    services:
      postgres:
        image: fryguy9/postgresql-with-config:latest
        env:
          POSTGRESQL_USER: root
          POSTGRESQL_PASSWORD: smartvm
          POSTGRESQL_DATABASE: temp
        options: "--name postgres --health-cmd pg_isready --health-interval 2s --health-timeout 5s
          --health-retries 5"
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Verify libpq
      run: ls -al /usr/lib
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby-version }}"
        bundler-cache: true
      timeout-minutes: 30
    - name: Set up tests
      run: bundle exec rake spec:setup
      env:
        POSTGRESQL_HOST: localhost
        POSTGRESQL_USER: root
        POSTGRESQL_PASSWORD: smartvm
    - name: Run tests
      run: bundle exec rake
      env:
        POSTGRESQL_HOST: localhost
        POSTGRESQL_USER: root
        POSTGRESQL_PASSWORD: smartvm
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    - if: ${{ github.ref == 'refs/heads/master' && matrix.ruby-version == '3.3' }}
      name: Report code coverage
      continue-on-error: true
      uses: paambaati/codeclimate-action@v9
      env:
        CC_TEST_REPORTER_ID: "${{ secrets.CC_TEST_REPORTER_ID }}"
